// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/hbtc-chain/bhchain/x/mint/internal/keeper
// ALIASGEN: github.com/hbtc-chain/bhchain/x/mint/internal/types
package mint

import (
	"github.com/hbtc-chain/bhchain/x/mint/internal/keeper"
	"github.com/hbtc-chain/bhchain/x/mint/internal/types"
)

const (
	ModuleName        = types.ModuleName
	DefaultParamspace = types.DefaultParamspace
	StoreKey          = types.StoreKey
	QuerierRoute      = types.QuerierRoute
	QueryParameters   = types.QueryParameters
	RouterKey         = types.RouterKey
)

var (
	// functions aliases
	NewKeeper            = keeper.NewKeeper
	NewQuerier           = keeper.NewQuerier
	ParamKeyTable        = types.ParamKeyTable
	NewParams            = types.NewParams
	DefaultParams        = types.DefaultParams
	ValidateParams       = types.ValidateParams
	NewMinter            = types.NewMinter
	InitialMinter        = types.InitialMinter
	DefaultInitialMinter = types.DefaultInitialMinter
	ValidateMinter       = types.ValidateMinter
	RegisterCodec        = types.RegisterCodec

	// variable aliases
	ModuleCdc       = types.ModuleCdc
	MinterKey       = types.MinterKey
	KeyMintDenom    = types.KeyMintDenom
	KeyMintPerBlock = types.KeyMintPerBlock
	KeyInflation    = types.KeyInflation
)

type (
	Keeper = keeper.Keeper
	Minter = types.Minter
	Params = types.Params
)
