// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/hbtc-chain/bhchain/x/genaccounts/internal/types
package genaccounts

import (
	"github.com/hbtc-chain/bhchain/x/genaccounts/internal/types"
)

const (
	ModuleName = types.ModuleName
)

var (
	// functions aliases
	NewGenesisCURaw             = types.NewGenesisCURaw
	NewGenesisCU                = types.NewGenesisCU
	NewGenesisCUI               = types.NewGenesisCUI
	GetGenesisStateFromAppState = types.GetGenesisStateFromAppState
	SetGenesisStateInAppState   = types.SetGenesisStateInAppState
	ValidateGenesis             = types.ValidateGenesis

	// variable aliases
	ModuleCdc = types.ModuleCdc
)

type (
	GenesisCU    = types.GenesisCU
	GenesisCUs   = types.GenesisCUs
	GenesisState = types.GenesisState
)
